server.port=${PORT:5000}

app.version=${APP_VERSION:@project.version@}
app.dynamodb.table=${DDB_TABLE_NAME:}
app.dynamodb.region=${AWS_REGION:eu-west-1}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
